version: '3.4'

services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:5.0.2
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
